COMPILER=gcc
COMPILER_ARGUMENTS=-Wall -std=c99

SOURCE_FILES=src/*.c

OUTPUT_FOLDER=target/
OUTPUT_FILE=bg_shell

build: $(FOLDER) 
	rm -rf $(OUTPUT_FOLDER)
	mkdir $(OUTPUT_FOLDER)
	$(COMPILER) $(COMPILER_ARGUMENTS) $(SOURCE_FILES) -o $(OUTPUT_FOLDER)$(OUTPUT_FILE) 
